# This file was generated by GoReleaser. DO NOT EDIT.
cask "foldersync-cli" do
  name "foldersync-cli"
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "foldersync-cli"

  on_macos do
    on_intel do
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Darwin_x86_64.tar.gz"
      sha256 "9ddfcaa4751e7515dc780d1c829ede20c35051fe62b722b20c9486a82a830898"
    end
    on_arm do
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Darwin_arm64.tar.gz"
      sha256 "c72a44ebe22d655e3f04f8e186dc826af3eb6056959624410b4d256630f02ed2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Linux_x86_64.tar.gz"
      sha256 "0f82b26bae4efb21cf0638103758b49902df932c7937a458c16a82fa7b026c34"
    end
    on_arm do
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Linux_arm64.tar.gz"
      sha256 "edbeaab1b23f949f072c9aff5f333e779c2e357a943c838809066a34d3cc0248"
    end
  end

  # No zap stanza required
end
