# This file was generated by GoReleaser. DO NOT EDIT.
cask "foldersync-cli" do
  name "foldersync-cli"
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "foldersync-cli"

  on_macos do
    on_intel do
      url "https://github.com/tacitdynamics/folderSync-cli/releases/download/v#{version}/foldersync-cli_Darwin_x86_64.tar.gz"
      sha256 "874431b84e8c22aa0a270fe127782d4197aa7c3809421115b76b5befc7dffbfc"
    end
    on_arm do
      url "https://github.com/tacitdynamics/folderSync-cli/releases/download/v#{version}/foldersync-cli_Darwin_arm64.tar.gz"
      sha256 "a8e98b0bbd02b5a922e87614f9123f428e86ab173ff6b187af22d3586c0e6ff7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tacitdynamics/folderSync-cli/releases/download/v#{version}/foldersync-cli_Linux_x86_64.tar.gz"
      sha256 "0b288f77af39554f138b9c25ef0bd80259b609b0af34c096740998f0f6407be0"
    end
    on_arm do
      url "https://github.com/tacitdynamics/folderSync-cli/releases/download/v#{version}/foldersync-cli_Linux_arm64.tar.gz"
      sha256 "77f5e9a2c765082ff744b3c85aea067ff9ecc1ff5c04e83e4dc6a4237e1ec601"
    end
  end

  # No zap stanza required
end
