# This file was generated by GoReleaser. DO NOT EDIT.
cask "foldersync-cli" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "d3037f35c98807f9df5a50f615d29a7c60b12e9f0379d631b83d644e5dadfa27"
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "50b8756e483c01d7769528340ba951c627716fafc12e7859469ff943789a92b1"
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2019f75a13ea70a96e97fb0917247e4207119fb90428bf80eb46cf496e521b7c"
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b84caca60fce1fbc8c39b864bbc362b64322f1ed06c8346017efd8b4e35e93cc"
      url "https://github.com/tacitdynamics/folderSync-cli-releases/releases/download/v#{version}/foldersync-cli_Linux_arm64.tar.gz"
    end
  end

  name "foldersync-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "foldersync-cli"

  # No zap stanza required

end
